/**
 * ui-texts.ts — the learner PWA's complete FR/EN interface copy, as data.
 *
 * Single source of truth shared by:
 *   - the learner PWA (`web/src/lib/i18n.tsx` renders from these defaults,
 *     overlaid with the super-admin overrides served by GET /ui-texts);
 *   - the admin console's « Textes de l'interface » editor (lists every key,
 *     shows the default, lets a SUPER_ADMIN override or revert).
 *
 * Keys are flat ("screen.element"); values may carry {var} placeholders that
 * are interpolated at render time — overrides must keep the same placeholders.
 */
export type UiLang = "fr" | "en";
export type UiDict = Record<string, string>;

const fr: UiDict = {
  // shell / navigation
  "nav.home": "Accueil", "nav.cours": "Cours", "nav.journal": "Journal", "nav.badges": "Badges",
  "nav.account": "Mon compte", "nav.logout": "Déconnexion",
  "brand.operatedBy": "Opéré par {operator}", "brand.myCourses": "Mes parcours",
  "banner.offline": "⚠️ Hors-ligne — votre progression est enregistrée et se synchronisera automatiquement.",
  "banner.syncing": "⟳ Synchronisation…", "a11y.notifications": "Notifications",
  // common
  "common.back": "Retour", "common.optional": "(optionnel)", "ph.email": "vous@exemple.com",
  // login
  "login.subtitle": "Connexion apprenant · opéré par {operator}",
  "login.email": "Email", "login.password": "Mot de passe", "login.signIn": "Se connecter",
  "login.forgot": "Mot de passe oublié ?", "login.noAccount": "Pas encore de compte ?",
  "login.create": "Créer un compte", "login.invalid": "Identifiants invalides",
  "login.unverified": "Votre e-mail n'est pas encore vérifié. Saisissez le code reçu (ou renvoyez-en un).",
  // signup
  "signup.subtitle": "Créer un compte · opéré par {operator}",
  "signup.fullName": "Nom complet", "signup.phone": "Téléphone",
  "signup.passwordMin": "10 caractères minimum",
  "signup.acceptPre": "J'accepte les ", "signup.terms": "conditions d'utilisation",
  "signup.and": " et la ", "signup.privacy": "politique de confidentialité",
  "signup.marketing": "J'accepte de recevoir des informations sur les offres et nouveautés",
  "signup.create": "Créer mon compte", "signup.already": "Déjà inscrit ?",
  "signup.mustAccept": "Vous devez accepter les conditions d'utilisation et la politique de confidentialité.",
  "signup.codeSent": "Un code de vérification a été envoyé à {email}.",
  "signup.fail": "Inscription impossible",
  // verify
  "verify.title": "Vérification", "verify.code": "Code de vérification", "verify.codePh": "6 chiffres",
  "verify.submit": "Vérifier et se connecter", "verify.resend": "Renvoyer le code",
  "verify.resent": "Nouveau code envoyé. Vérifiez votre boîte mail (et les indésirables).",
  "verify.invalid": "Code invalide",
  // forgot / reset
  "forgot.title": "Mot de passe oublié",
  "forgot.intro": "Saisissez votre e-mail : nous vous enverrons un code pour définir un nouveau mot de passe.",
  "forgot.send": "Envoyer le code",
  "forgot.sent": "Si un compte existe pour {email}, un code de réinitialisation a été envoyé.",
  "reset.title": "Nouveau mot de passe", "reset.codeReceived": "Code reçu",
  "reset.submit": "Réinitialiser et se connecter", "reset.resent": "Nouveau code envoyé.",
  "reset.fail": "Réinitialisation impossible",
  // install prompt
  "install.title": "Installer l'app", "install.sub": "Accès rapide, plein écran, hors-ligne.",
  "install.ios": "Appuyez sur Partager ⬆️ puis « Sur l'écran d'accueil ».",
  "install.cta": "Installer", "install.close": "Fermer", "install.aria": "Installer l'application",
  // levels / common
  "common.loading": "Chargement…", "common.error": "Erreur",
  "level.1": "Niveau 1", "level.2": "Niveau 2", "level.3": "Niveau 3",
  // enrolments list
  "enr.myCourses": "Mes parcours",
  "enr.loadError": "Impossible de charger vos parcours (hors-ligne ?).",
  "enr.offlineAvailable": "Parcours disponibles hors-ligne :",
  "enr.open": "Ouvrir {id}…",
  "enr.none": "Vous n'êtes encore inscrit·e à aucun parcours. Choisissez-en un ci-dessous 👇",
  "enr.certified": "Certifié 🎓", "enr.blocks": "{done}/{total} blocs · {pct}%",
  "enr.available": "Parcours disponibles", "enr.enrollOneClick": "Inscrivez-vous en un clic.",

  // achat (paiement B2C)
  "pay.title": "Acheter le parcours",
  "pay.currency": "Devise",
  "pay.oneTime": "Paiement unique — accès complet au parcours, en ligne et hors ligne.",
  "pay.buy": "Acheter",
  "pay.buying": "Redirection…",
  "pay.buyFail": "Achat impossible pour le moment",
  "pay.back": "Retour au catalogue",
  "pay.loadError": "Impossible de charger les informations d'achat",
  "pay.orderTitle": "Ma commande",
  "pay.statusPending": "En attente",
  "pay.statusPaid": "Payée",
  "pay.statusFailed": "Échouée",
  "pay.pendingHint": "Votre paiement est en cours de confirmation — cette page se met à jour automatiquement.",
  "pay.payNow": "Payer maintenant",
  "pay.paidHint": "Paiement confirmé ! Votre accès au parcours est débloqué.",
  "pay.enterCourse": "Commencer le parcours",
  "pay.receipt": "Télécharger le reçu (PDF)",
  "pay.receiptFail": "Reçu indisponible pour le moment",
  "pay.failedHint": "Le paiement n'a pas abouti. Vous pouvez réessayer — aucun montant n'est débité sur une commande échouée.",
  "pay.retry": "Réessayer",
  "pay.enrollFail": "Inscription impossible pour le moment",
  "pay.guestEmail": "Votre adresse e-mail",
  "pay.guestEmailHint": "Aucun compte à créer maintenant : votre reçu et votre lien d'accès y seront envoyés après le paiement.",
  "pay.guestPhoneNote": "Le numéro Mobile Money est saisi sur la page sécurisée de paiement, pas ici.",
  "pay.emailInvalid": "Adresse e-mail invalide",
  "pay.alreadyEntitled": "Vous avez déjà accès à ce parcours — un lien de connexion vient d'être envoyé à votre adresse e-mail.",
  "pay.checkEmail": "Votre reçu et un lien de connexion en un clic ont été envoyés à votre adresse e-mail (valable 72 h).",
  "pay.courseFree": "Ce parcours est en accès libre — créez simplement un compte pour vous y inscrire.",
  "pay.goLogin": "Aller à la connexion",
  "pay.magicTitle": "Connexion en un clic",
  "pay.magicWorking": "Connexion en cours…",
  "pay.magicFail": "Ce lien de connexion est invalide ou a expiré. Demandez-en un nouveau depuis « Mot de passe oublié », ou refaites un achat.",
  "pay.orderLost": "Suivi indisponible sur cet appareil — le lien de suivi a expiré ou l'achat a été fait ailleurs. Consultez l'e-mail reçu.",
  "enr.enrolling": "Inscription…", "enr.enroll": "S'inscrire →", "enr.enrollFail": "Inscription impossible",
  // account
  "acc.title": "Mon compte & confidentialité", "acc.consents": "Mes consentements", "acc.required": " (requis)",
  "acc.accepted": "Accepté", "acc.acceptedOn": " le {date}", "acc.notAccepted": "Non accepté",
  "acc.consentsNote": "Les consentements requis ne peuvent être retirés ici : cela reviendrait à supprimer le compte.",
  "acc.myData": "Mes données",
  "acc.myDataDesc": "Téléchargez une copie de toutes vos données (profil, progression, journal…) au format JSON — droit d'accès et portabilité.",
  "acc.export": "⬇ Exporter mes données",
  "acc.exported": "Vos données ont été téléchargées (mes-donnees.json).",
  "acc.deleteTitle": "Supprimer mon compte",
  "acc.deleteDesc": "Votre compte sera bloqué immédiatement puis effacé après 30 jours. Réversible pendant ce délai via le support.",
  "acc.deleteConfirm": "Supprimer votre compte ?\n\nIl sera bloqué immédiatement, puis effacé après un délai de grâce de 30 jours. Contactez le support avant cette date pour annuler.",
  "acc.deleteScheduled": "Votre compte a été programmé pour suppression. Vous êtes maintenant déconnecté.",
  // home
  "home.hello": "Bonjour {name}", "home.resume": "Reprendre", "home.block": "Bloc {n}",
  "home.exactResume": "↺ Reprise exacte", "home.video": "vidéo {time}", "home.resumeBtn": "Reprendre →",
  "home.courseDone": "Parcours terminé 🎓",
  "home.priorities": "🎯 Vos axes prioritaires", "home.prioritiesDesc": "D'après votre diagnostic, concentrez-vous sur :",
  "home.review": "Revoir mes points à améliorer →", "home.goToCourse": "Aller au cours",
  "home.progress": "Progression", "home.blocksCount": "{done} / {total} blocs",
  "home.prodScore": "Score de productivité", "home.prodDesc": "Monte à chaque exercice complété",
  "home.yourPath": "Votre parcours", "home.peer": "Pair de progression", "home.notified": "✓ Notifié",
  // course
  "course.state.done": "Terminé", "course.state.locked": "🔒 Verrouillé", "course.state.inProgress": "En cours",
  "course.title": "Le parcours", "course.unavailable": "Parcours indisponible (hors-ligne et non rendu disponible).",
  "course.priorities": "🎯 Vos priorités d'apprentissage",
  "course.ms_s": "micro-session", "course.ms_p": "micro-sessions",
  "course.la_s": "activité longue", "course.la_p": "activités longues",
  "course.mt_s": "micro-tâche", "course.mt_p": "micro-tâches",
  "course.markDone": "Terminé", "course.availOffline": "✓ Disponible hors ligne · {days} j",
  "course.remove": "Retirer", "course.makeOffline": "⤓ Rendre disponible hors ligne",
  "course.availMsg": "« {label} » disponible hors ligne ({cached}/{total}) · 7 jours.",
  "course.availMsgSimple": "« {label} » disponible hors ligne · 7 jours.",
  "course.lockAfter43": "s'ouvre après la micro-session 4.3",
  "course.lockUntil": "s'ouvre le {date} (vous serez notifié·e)",
  "course.lockFinalSection": "s'ouvre après les sections 1-3",
  "course.recallTitle": "Rappel du Bloc {n} avant de reprendre",
  // Jalons « À vous de jouer » (arbitrage A5) : la mise en pratique se fait EN
  // PARALLÈLE du parcours — dit explicitement à l'entrée des blocs 2 et 3.
  "course.yourTurnTitle": "À vous de jouer",
  "course.yourTurnPractice": "dans ce bloc, la mise en pratique se fait en parallèle, dans votre vrai travail : testez vos outils sur le terrain au fil des exercices — l'Application terrain vous demandera ce que vous avez réellement essayé.",
  "course.yourTurnAnchoring": "continuez d'appliquer vos outils dans votre travail pendant ce bloc : le Plan d'action 30 jours et le journal de bord s'appuieront sur ce que vous testez réellement.",
  "course.recallDuration": "2 min",
  "ob.peerConsent": "J'accepte que la plateforme informe mon pair de mes avancées (badges obtenus) par e-mail. Sans cette case, votre pair est nommé mais ne reçoit aucune notification.",
  "ch.eyebrow": "Votre cohorte",
  "ch.courseCard": "Ma cohorte — progression du groupe & forum",
  "ch.offline": "La cohorte et le forum nécessitent une connexion. Réessayez en ligne.",
  "ch.none": "Vous n'êtes rattaché·e à aucune cohorte pour ce parcours. Les cohortes sont créées par votre organisation ou par l'équipe pédagogique.",
  "ch.boardTitle": "Progression du groupe",
  "ch.members": "{n} membre(s)",
  "ch.blocksDone": "{n} bloc(s) validé(s)",
  "ch.certified": "Certifié·e·s",
  "ch.avg": "Progression moyenne : {pct} %",
  "ch.certCount": "{n} certifié·e·s",
  "ch.anonNote": "Progression agrégée de la cohorte — personne n'est identifié individuellement.",
  "ch.forumTitle": "Forum de pratique",
  "ch.newThread": "Nouveau fil",
  "ch.threadTitlePh": "Titre du fil (ex. « Comment protégez-vous votre créneau du matin ? »)",
  "ch.threadBodyPh": "Votre message — partagez une situation de terrain, une difficulté, une astuce…",
  "ch.publish": "Publier",
  "ch.noThreads": "Aucun fil pour l'instant. Lancez la première discussion : une situation vécue pendant vos exercices terrain est un excellent point de départ.",
  "ch.replies": "{n} réponse(s)",
  "ch.reply": "Répondre",
  "ch.replyPh": "Votre réponse…",
  "ch.locked": "Fil verrouillé par la modération.",
  "ch.anonymous": "Membre de la cohorte",
  // onboarding
  "ob.invalidPeer": "Indiquez un nom et un e-mail valides.", "ob.step": "Étape {n} sur 3",
  "ob.startingPoint": "Votre point de départ", "ob.pamTag": "🎯 Moment d'Ancrage",
  // Écran « Comment cette formation fonctionne » (arbitrage A5) : la méthode
  // est énoncée AVANT de commencer — l'apprenant découvre tout pour la 1re fois.
  "ob.howTitle": "Comment cette formation fonctionne",
  "ob.howIntro": "Deux minutes pour comprendre la méthode — elle est différente d'une formation classique.",
  "ob.how1": "📱 Des micro-sessions de 15 à 25 minutes, sur mobile ou ordinateur, avec reprise automatique là où vous vous êtes arrêté·e. Vos réponses écrites nourrissent la suite du parcours : une fois validées, elles sont définitives.",
  "ob.how2": "🎯 La mise en pratique se fait EN PARALLÈLE, dans votre vrai travail : dès le Bloc 2, les exercices vous demandent de tester vos outils sur le terrain — pas seulement d'y réfléchir.",
  "ob.how3": "📓 Le journal de bord est à part : 6 micro-entrées de 5 minutes, débloquées au fil de 15 jours de pratique réelle (J+2 → J+15). Vous recevrez un e-mail à chaque ouverture, et un rappel si vous oubliez. Le projet final s'appuie dessus — on ne peut pas le précipiter.",
  "ob.how4": "🤝 Votre pair de progression : une personne de confiance que vous désignez au départ et avec qui vous partagez vos avancées — c'est l'un des secrets des parcours menés à terme.",
  "ob.how5": "🎓 La certification : un mini-projet ancré dans votre réalité, évalué par un évaluateur humain avec une grille transparente — seuil 70/100 ET un minimum par critère : aucune moyenne ne compense un critère insuffisant.",
  "ob.howCta": "J'ai compris, je commence →",
  "ob.pamPlaceholder": "Décrivez votre situation professionnelle réelle…", "ob.saveContinue": "Enregistrer et continuer →",
  "ob.objective": "🎯 Objectif du parcours", "ob.whichProfile": "Quel profil vous correspond le mieux ?", "ob.continue": "Continuer →",
  "ob.peerTitle": "Votre pair de progression", "ob.peerDescPre": "Choisissez une personne qui sera informée de vos réussites. ",
  "ob.peerMandatory": "Étape obligatoire", "ob.peerDescPost": " — la responsabilisation sociale fait partie du parcours.",
  "ob.name": "Nom", "ob.namePh": "Nom du collègue / mentor", "ob.email": "E-mail", "ob.emailPh": "email@exemple.com",
  "ob.validate": "Valider mon pair de progression", "ob.medal": "Entré", "ob.doneTitle": "Micro-session 0.1 — Onboarding terminée !",
  "ob.doneDesc": "Il reste une étape avant votre badge d'entrée : la vidéo déclencheur. Elle démarre juste après.", "ob.startCourse": "Continuer le parcours →",
  // session
  "sess.unavailableOffline": "Parcours indisponible hors-ligne.", "sess.triggerVideo": "Vidéo déclencheur",
  "sess.thisSession": "⏱️ Cette micro-session : {dur}", "sess.recall": "↩︎ Rappel — {title}", "sess.keyTakeaway": "À retenir",
  "sess.videoUnavailable": "⚠️ La vidéo n'est pas disponible pour le moment. Vous pouvez tout de même poursuivre la micro-session.",
  "sess.skipExercise": "Passer à l'exercice →", "sess.finishSession": "Terminer la micro-session →",
  // shared
  "nav.backCourse": "← Cours", "common.continue": "Continuer →", "common.cancel": "Annuler", "home.remaining": "Il reste ≈ {dur}",
  "home.remainingSplit": "Bloc en cours : ≈ {block} · Parcours : ≈ {all}",
  "home.startBtn": "Démarrer →",
  "crumb.blockDur": "Bloc {n} · {title} — {dur}", "crumb.itemDur": "{label} — {dur}",
  "sess.fullscreenHint": "💡 Conseil : regardez en plein écran (⛶). Le texte qui se déplace sur la vidéo (votre nom/e-mail) est un filigrane anti-partage — c'est normal.",
  "quiz.profileSaved": "Profil enregistré — toutes les réponses sont valables",
  "sess.toTriggerQuiz": "Continuer vers le quiz déclencheur →",
  "sess.triggerQuizTitle": "Quiz déclencheur — {n} questions rapides (non noté, il affine votre profil)",
  "sess.triggerQuizGo": "Valider mes réponses",
  "mission": "🎯 Votre mission", "answerPlaceholder": "Votre réponse, ancrée dans votre situation réelle…",
  // text-quality gate (3e point « Amélioration »)
  "tc.gibberish": "⚠️ Certains mots ne semblent exister ni en français ni en anglais : {words}. Corrigez votre réponse pour continuer — la plateforme attend des phrases qui ont du sens.",
  "tc.tooShort": "⚠️ Formulez une réponse complète (au moins {n} mots).",
  "tc.needNumber": "⚠️ Ce champ attend une valeur chiffrée — écrivez un chiffre (ex. « 25 % », « 90 minutes ») ou son équivalent en lettres (« vingt-cinq pour cent »).",
  "tc.charsLeft": "✍️ Encore {n} caractères (lettres et espaces, pas des mots) avant de pouvoir valider — développez votre réponse.",
  "tc.filler": "⚠️ Votre réponse ressemble à du texte de remplissage ({words}…). Cet exercice nourrit la suite de votre parcours — répondez avec votre situation réelle.",
  // Compteurs de saisie (P8) : le seuil est un MINIMUM, jamais un plafond —
  // atteint, le compteur cesse d'afficher « / seuil » pour ne pas brider.
  "count.min": "{n} / {min} {unit} minimum",
  "count.ok": "{n} {unit} ✓",
  // quiz
  "qz.diagnostic": "Quiz diagnostique", "qz.interblock": "Quiz interbloc", "qz.final": "Quiz final",
  "qz.unavailable": "Quiz indisponible.", "qz.profileTitle": "Votre profil de compétence",
  "qz.priorities": "Vos priorités d'apprentissage", "qz.priority1": "Votre priorité d'apprentissage", "qz.score": "Score : {correct}/{total}",
  "qz.notScored": "Ce quiz n'est pas noté : il établit votre profil de départ, et vos priorités d'apprentissage ci-dessus découlent directement de vos réponses.",
  "qz.finalPassed": "Quiz final réussi !", "qz.finalNotYet": "Pas encore atteint",
  "qz.thresholdPill": "{pct}% · seuil {threshold}%", "qz.finalPassedDesc": "Le bloc de certification est débloqué.",
  "qz.finalFailDesc": "Reprenez les sessions du bloc puis retentez.",
  "qz.consolidationDone": "Consolidation terminée", "qz.correctCount": "{correct}/{total} bonnes réponses",
  "qz.noPriorities": "Aucune lacune détectée — toutes les thématiques sont maîtrisées. Poursuivez le parcours pour consolider vos réflexes.",
  "qz.selfDiverges": "Vous vous étiez reconnu·e dans « {self} ». Votre diagnostic en situation vous situe « {band} » : les deux s'écartent — c'est le diagnostic qui fait autorité pour la suite du parcours.",
  "qz.selfConfirms": "Votre diagnostic en situation (« {band} ») est cohérent avec le profil dans lequel vous vous étiez reconnu·e (« {self} »).",
  "qz.selfNeutral": "Vous vous étiez reconnu·e dans « {self} ». Votre diagnostic en situation vous situe « {band} » — c'est lui qui fait autorité pour la suite du parcours.",
  "act.scenarioContext": "Contexte", "act.scenarioOf": "Situation {n} / {total}", "act.scenarioDone": "Mises en situation terminées !",
  "act.selfIntro": "Situez-vous honnêtement sur chaque affirmation — il n'y a pas de bonne ou de mauvaise réponse, c'est votre point de mesure avant le plan d'action.",
  "act.planIntro": "Votre plan des 30 prochains jours : une habitude à la fois. Décrivez concrètement chaque habitude — c'est ce que votre pair de progression suivra.",
  "act.caseIntro": "Lisez les étapes du cas, puis rédigez votre analyse : elle est enregistrée et réutilisée au Bloc 4.",
  "act.caseAnswer": "Votre analyse (transfert à votre situation)",
  "act.caseContext": "Contexte", "act.caseStepOf": "Étape {n} sur {total}",
  "act.caseSaved": "💾 Réponse enregistrée pour le projet certifiant du Bloc 4.",
  "act.caseAllValid": "Toutes les réponses sont valables — choisissez celle qui correspond à votre situation.",
  "act.caseSummary": "Résumé des apprentissages clés", "act.caseDone": "Étude de cas terminée !",
  "act.openAnswerPh": "Votre réponse…",
  "ex.aiTitle": "Retour personnalisé sur votre réponse", "ex.aiLoading": "Analyse de votre réponse en cours…",
  "badge.unlocked": "Badge débloqué !", "badge.peerNotified": "🤝 Votre pair de progression est prévenu",
  // journal
  "jr.eyebrow": "Journal de bord", "jr.title": "Ancrer mes acquis",
  "jr.intro": "Une micro-entrée à des intervalles clés, ancrée dans votre situation réelle (votre Moment d'Ancrage). Ces entrées composent la Section 4 de votre projet et comptent dans la notation : la régularité de la pratique est un critère de la grille, avec un minimum exigé.",
  "jr.day": "Jour J+{n}",
  // badges
  "bd.eyebrow": "Vos badges", "bd.title": "Progression certifiante", "bd.obtained": "Obtenu",
  "bd.entry": "Badge Entrée", "bd.comprehension": "Badge Compréhension", "bd.practice": "Badge Pratique", "bd.anchoring": "Badge Ancrage",
  "bd.addLinkedIn": "Ajouter à LinkedIn", "bd.verify": "Vérifier", "bd.certOf": "Certification de {level}",
  "bd.publicVerify": "Vérification publique", "bd.submitProject": "Déposer mon projet du Bloc 4 →",
  "bd.blockBadges": "Badges de fin de bloc", "bd.finalCert": "Certification finale",
  "bd.certNote": "Les badges jalonnent la progression — seule la certification finale, validée par un évaluateur, vaut certification.",
  "bd.download": "⬇ Télécharger (PDF)", "bd.transcript": "Relevé de résultats (quiz et activités notés)",
  "bd.notGraded": "non noté",
  // deliverable
  "dl.fieldEyebrow": "Application terrain — obligatoire", "dl.fieldTitle": "Application terrain",
  "dl.journalTitle": "Journal — Jour {key}", "dl.unitChars": "caractères", "dl.unitWords": "mots",
  "dl.notFound": "Élément introuvable.", "dl.submit": "Soumettre →", "dl.submitted": "Réponse soumise !",
  "dl.journalLockedAt": "Cette micro-entrée s'ouvrira le {date} (J+{day} après la micro-session 4.3). Vous recevrez une notification à ce moment-là.",
  "dl.journalLockedAfter43": "Le journal des 2 semaines s'ouvre après la micro-session 4.3 (Section 3) — ses micro-entrées se déverrouillent ensuite une à une (J+2 → J+15).",
  // project
  "pj.unavailable": "Projet indisponible.", "pj.eyebrow": "Bloc 4 · Certification", "pj.title": "Projet de certification",
  "pj.st.submitted": "Soumis — en attente d'attribution", "pj.st.assigned": "En cours d'évaluation",
  "pj.st.passed": "Certifié 🎓", "pj.st.revision": "Remise demandée — une reprise unique sous 30 jours, revue par le même évaluateur",
  "pj.st.notCertified": "Non certifié — une reprise des Blocs 2 ou 3 est conseillée avant une nouvelle soumission",
  "pj.submittedOn": "Soumis le {date}", "pj.evaluator": "Évaluateur : {name}",
  "pj.scoreLine": "Score : {score}/100", "pj.scoreThreshold": "(seuil {threshold})", "pj.evalFeedback": "Retour de l'évaluateur",
  "pj.appeal.title": "Contester la décision (recours)",
  "pj.appeal.intro": "Vous pouvez contester par écrit dans les 15 jours calendaires suivant la décision : cochez les critères contestés et indiquez les éléments de votre dossier que vous estimez non pris en compte. Votre dossier sera re-noté à l'aveugle par un autre évaluateur. La décision issue du recours est finale.",
  "pj.appeal.statementPh": "Éléments de mon dossier non pris en compte…",
  "pj.appeal.submit": "Déposer le recours →",
  "pj.appeal.pickOne": "Cochez au moins un critère contesté.",
  "pj.appeal.status.OPEN": "Recours déposé — désignation d'un second évaluateur en cours",
  "pj.appeal.status.SECOND_ASSIGNED": "Recours en cours — re-notation à l'aveugle par un second évaluateur",
  "pj.appeal.status.THIRD_REQUIRED": "Recours en cours — un troisième évaluateur va trancher",
  "pj.appeal.status.THIRD_ASSIGNED": "Recours en cours — décision du troisième évaluateur attendue",
  "pj.appeal.status.DECIDED": "Recours instruit — décision finale : {total}/100",
  "pj.appeal.final": "La décision issue du recours est finale.",
  "pj.rubricTitle": "Grille d'évaluation", "pj.rubricNote": "(visible avant de soumettre — dépliez chaque critère)",
  "pj.pts": "{n} pts", "pj.passThreshold": "Seuil de réussite : {threshold}/100",
  "pj.rubricMin": "min. {min}", "pj.whereToLook": "Où l'évaluateur cherche la preuve : {text}",
  "pj.band": "Bande {band} · {lo}–{hi} pts",
  "pj.decisionTitle": "Comment la décision est prise",
  "pj.decisionCertified": "Certifié : total ≥ {threshold}/100 ET chaque critère à son minimum — aucune moyenne ne compense un critère insuffisant.",
  "pj.decisionResubmit": "Remise demandée : total sous le seuil, ou UN critère sous son minimum — une seule reprise, sous 30 jours, revue par le même évaluateur.",
  "pj.decisionNotCertified": "Non certifié : deux critères sous leur minimum, ou total inférieur à 55/100.",
  "pj.writeTip": "✍️ Rédigez des phrases complètes, avec des exemples concrets, datés et situés dans votre contexte : l'évaluation s'appuie sur des citations exactes de votre dossier — un texte développé est votre meilleure preuve.",
  "pj.minMet": "minimum atteint ({min})", "pj.minMissed": "sous le minimum ({min})",
  "pj.words": "{count} mots — minimum {min}",
  "pj.submit": "Soumettre mon projet →", "pj.complete5": "Complétez les 5 sections pour soumettre.",
  "pj.sectionDone": "✓ Section soumise", "pj.submitSection": "Soumettre cette section →",
  "pj.sectionLocked": "🔒 S'ouvre après les sections 1 à 3. Les entrées de journal manquantes ne bloquent pas la soumission, mais pèsent sur la note : la régularité de la pratique est un critère de la grille, avec un minimum exigé.",
  "pj.section4Auto": "Cette section se remplit automatiquement, chapitre par chapitre, à partir de vos 6 micro-entrées de journal (J+2 → J+15). Elle n'est pas saisissable directement.",
  "pj.section4Waiting": "En attente de vos micro-entrées de journal…",
  "pj.finalNote": "La soumission de cette section assemble et dépose l'ensemble du projet pour l'évaluation.",
  // exercise
  "ex.eyebrow": "Micro-exercice — obligatoire", "ex.validate": "Valider ma réponse",
  "ex.correct": "✓ Bonne réponse", "ex.review": "À revoir", "ex.feedback": "Feedback immédiat", "ex.next": "Session suivante →",
  // revision
  "rev.eyebrow": "Révision personnalisée", "rev.title": "Vos points à améliorer",
  "rev.noQuiz": "Passez d'abord le quiz diagnostique pour obtenir une révision personnalisée.",
  "rev.noErrors": "🎉 Aucune erreur au diagnostique — rien à réviser pour l'instant !",
  "rev.intro": "Les questions ratées au diagnostique. Relisez la bonne réponse et l'explication pour renforcer vos acquis (sans note).",
  "rev.goodAnswer": " — bonne réponse", "rev.yourAnswer": " — votre réponse", "rev.why": "Pourquoi", "rev.resume": "Reprendre le parcours →",
  // video player
  "vp.speed": "Vitesse", "vp.speedAria": "Vitesse de lecture", "vp.quality": "Qualité", "vp.auto": "Auto",
  "vp.subtitles": "Sous-titres", "vp.stOff": "Désactivés",
  "vp.source": "Source (max)", "vp.720p": "720p (HD)", "vp.480p": "480p", "vp.240p": "240p — éco data", "vp.audio": "Audio seul",
  // course item labels
  "ci.onboarding": "Introduction & point de départ", "ci.case": "Étude de cas", "ci.scenarios": "Mises en situation guidées",
  "ci.self": "Auto-évaluation", "ci.plan": "Plan d'action 30 jours", "ci.journal": "Journal J+{day}",
  "ci.msPrefix": "Micro-session", "ci.ms01": "Micro-session 0.1 — Onboarding", "ci.ms02": "Micro-session 0.2 — Déclencheur",
  "ci.ms02sub": "Vidéo déclencheur + Quiz (non noté)", "ci.transversal": "Cas transversal de synthèse",
  "ci.journalGroup": "Journal des 2 semaines",
  // quiz component (one question at a time)
  "quiz.q": "Question {n} / {total}", "quiz.validate": "Valider", "quiz.good": "✓ Bonne réponse", "quiz.review": "À revoir",
  "quiz.seeResult": "Voir mon résultat →", "quiz.nextQuestion": "Question suivante →",
  "quiz.multiHint": "Plusieurs réponses possibles", "quiz.true": "Vrai", "quiz.false": "Faux",
  "quiz.numPlaceholder": "Votre réponse (nombre)", "quiz.expected": "Réponse attendue : {n}",
  // frozen results (première soumission définitive)
  "frz.note": "Réponses enregistrées lors de votre première tentative — consultables mais non modifiables.",
  "frz.yourAnswer": "Votre réponse",
  "frz.viewAnswer": "Voir ma réponse",
  "frz.resultTitle": "Vos résultats",
  "frz.retake": "Tentative précédente : {pct} % (seuil : {threshold} %). Ce quiz doit être repassé pour débloquer la suite.",
  "course.retakeFinal": "À repasser",
  "quiz.shortPlaceholder": "Votre réponse", "quiz.accepted": "Réponses acceptées : {list}",
};

const en: UiDict = {
  "nav.home": "Home", "nav.cours": "Course", "nav.journal": "Journal", "nav.badges": "Badges",
  "nav.account": "My account", "nav.logout": "Log out",
  "brand.operatedBy": "Operated by {operator}", "brand.myCourses": "My courses",
  "banner.offline": "⚠️ Offline — your progress is saved and will sync automatically.",
  "banner.syncing": "⟳ Syncing…", "a11y.notifications": "Notifications",
  "common.back": "Back", "common.optional": "(optional)", "ph.email": "you@example.com",
  "login.subtitle": "Learner sign-in · operated by {operator}",
  "login.email": "Email", "login.password": "Password", "login.signIn": "Sign in",
  "login.forgot": "Forgot password?", "login.noAccount": "No account yet?",
  "login.create": "Create an account", "login.invalid": "Invalid credentials",
  "login.unverified": "Your e-mail is not verified yet. Enter the code you received (or request a new one).",
  "signup.subtitle": "Create an account · operated by {operator}",
  "signup.fullName": "Full name", "signup.phone": "Phone",
  "signup.passwordMin": "10 characters minimum",
  "signup.acceptPre": "I accept the ", "signup.terms": "terms of use",
  "signup.and": " and the ", "signup.privacy": "privacy policy",
  "signup.marketing": "I agree to receive information about offers and news",
  "signup.create": "Create my account", "signup.already": "Already registered?",
  "signup.mustAccept": "You must accept the terms of use and the privacy policy.",
  "signup.codeSent": "A verification code was sent to {email}.",
  "signup.fail": "Sign-up failed",
  "verify.title": "Verification", "verify.code": "Verification code", "verify.codePh": "6 digits",
  "verify.submit": "Verify and sign in", "verify.resend": "Resend code",
  "verify.resent": "New code sent. Check your inbox (and spam folder).",
  "verify.invalid": "Invalid code",
  "forgot.title": "Forgot password",
  "forgot.intro": "Enter your e-mail: we'll send you a code to set a new password.",
  "forgot.send": "Send code",
  "forgot.sent": "If an account exists for {email}, a reset code has been sent.",
  "reset.title": "New password", "reset.codeReceived": "Code received",
  "reset.submit": "Reset and sign in", "reset.resent": "New code sent.",
  "reset.fail": "Reset failed",
  "install.title": "Install the app", "install.sub": "Quick access, full screen, offline.",
  "install.ios": "Tap Share ⬆️ then “Add to Home Screen”.",
  "install.cta": "Install", "install.close": "Close", "install.aria": "Install the application",
  "common.loading": "Loading…", "common.error": "Error",
  "level.1": "Level 1", "level.2": "Level 2", "level.3": "Level 3",
  "enr.myCourses": "My courses",
  "enr.loadError": "Couldn't load your courses (offline?).",
  "enr.offlineAvailable": "Courses available offline:",
  "enr.open": "Open {id}…",
  "enr.none": "You're not enrolled in any course yet. Pick one below 👇",
  "enr.certified": "Certified 🎓", "enr.blocks": "{done}/{total} blocks · {pct}%",
  "enr.available": "Available courses", "enr.enrollOneClick": "Enrol in one click.",

  // purchase (B2C payment)
  "pay.title": "Buy this course",
  "pay.currency": "Currency",
  "pay.oneTime": "One-time payment — full access to the course, online and offline.",
  "pay.buy": "Buy",
  "pay.buying": "Redirecting…",
  "pay.buyFail": "Purchase unavailable right now",
  "pay.back": "Back to catalogue",
  "pay.loadError": "Could not load purchase information",
  "pay.orderTitle": "My order",
  "pay.statusPending": "Pending",
  "pay.statusPaid": "Paid",
  "pay.statusFailed": "Failed",
  "pay.pendingHint": "Your payment is being confirmed — this page refreshes automatically.",
  "pay.payNow": "Pay now",
  "pay.paidHint": "Payment confirmed! Your course access is unlocked.",
  "pay.enterCourse": "Start the course",
  "pay.receipt": "Download receipt (PDF)",
  "pay.receiptFail": "Receipt unavailable right now",
  "pay.failedHint": "The payment did not go through. You can retry — nothing is charged on a failed order.",
  "pay.retry": "Retry",
  "pay.enrollFail": "Enrolment unavailable right now",
  "pay.guestEmail": "Your email address",
  "pay.guestEmailHint": "No account needed now: your receipt and access link will be sent there after payment.",
  "pay.guestPhoneNote": "Your Mobile Money number is entered on the secure payment page, not here.",
  "pay.emailInvalid": "Invalid email address",
  "pay.alreadyEntitled": "You already have access to this course — a sign-in link has just been sent to your email address.",
  "pay.checkEmail": "Your receipt and a one-click sign-in link have been sent to your email address (valid 72 h).",
  "pay.courseFree": "This course is free to access — simply create an account to enrol.",
  "pay.goLogin": "Go to sign-in",
  "pay.magicTitle": "One-click sign-in",
  "pay.magicWorking": "Signing you in…",
  "pay.magicFail": "This sign-in link is invalid or has expired. Request a new one via “Forgot password”, or purchase again.",
  "pay.orderLost": "Tracking unavailable on this device — the tracking link expired or the purchase was made elsewhere. Check the email you received.",
  "enr.enrolling": "Enrolling…", "enr.enroll": "Enrol →", "enr.enrollFail": "Enrolment failed",
  "acc.title": "My account & privacy", "acc.consents": "My consents", "acc.required": " (required)",
  "acc.accepted": "Accepted", "acc.acceptedOn": " on {date}", "acc.notAccepted": "Not accepted",
  "acc.consentsNote": "Required consents can't be withdrawn here: that would amount to deleting the account.",
  "acc.myData": "My data",
  "acc.myDataDesc": "Download a copy of all your data (profile, progress, journal…) as JSON — right of access and portability.",
  "acc.export": "⬇ Export my data",
  "acc.exported": "Your data has been downloaded (mes-donnees.json).",
  "acc.deleteTitle": "Delete my account",
  "acc.deleteDesc": "Your account will be blocked immediately, then erased after 30 days. Reversible during that period via support.",
  "acc.deleteConfirm": "Delete your account?\n\nIt will be blocked immediately, then erased after a 30-day grace period. Contact support before that date to cancel.",
  "acc.deleteScheduled": "Your account has been scheduled for deletion. You are now logged out.",
  "home.hello": "Hello {name}", "home.resume": "Resume", "home.block": "Block {n}",
  "home.exactResume": "↺ Exact resume", "home.video": "video {time}", "home.resumeBtn": "Resume →",
  "home.courseDone": "Course completed 🎓",
  "home.priorities": "🎯 Your priority areas", "home.prioritiesDesc": "Based on your diagnostic, focus on:",
  "home.review": "Review my areas to improve →", "home.goToCourse": "Go to the course",
  "home.progress": "Progress", "home.blocksCount": "{done} / {total} blocks",
  "home.prodScore": "Productivity score", "home.prodDesc": "Rises with each completed exercise",
  "home.yourPath": "Your path", "home.peer": "Progress peer", "home.notified": "✓ Notified",
  "course.state.done": "Completed", "course.state.locked": "🔒 Locked", "course.state.inProgress": "In progress",
  "course.title": "The course", "course.unavailable": "Course unavailable (offline and not made available).",
  "course.priorities": "🎯 Your learning priorities",
  "course.ms_s": "micro-session", "course.ms_p": "micro-sessions",
  "course.la_s": "long activity", "course.la_p": "long activities",
  "course.mt_s": "micro-task", "course.mt_p": "micro-tasks",
  "course.markDone": "Done", "course.availOffline": "✓ Available offline · {days}d",
  "course.remove": "Remove", "course.makeOffline": "⤓ Make available offline",
  "course.availMsg": "“{label}” available offline ({cached}/{total}) · 7 days.",
  "course.availMsgSimple": "“{label}” available offline · 7 days.",
  "course.lockAfter43": "opens after micro-session 4.3",
  "course.lockUntil": "opens on {date} (you'll be notified)",
  "course.lockFinalSection": "opens after sections 1-3",
  "course.recallTitle": "Block {n} recap before you resume",
  "course.yourTurnTitle": "Your turn",
  "course.yourTurnPractice": "in this block, practice happens in parallel, in your real work: test your tools in the field as you go — the field application will ask what you actually tried.",
  "course.yourTurnAnchoring": "keep applying your tools at work during this block: the 30-day action plan and the logbook will build on what you actually test.",
  "course.recallDuration": "2 min",
  "ob.peerConsent": "I agree that the platform may inform my peer of my progress (badges earned) by e-mail. Without this box, your peer is named but receives no notification.",
  "ch.eyebrow": "Your cohort",
  "ch.courseCard": "My cohort — group progress & forum",
  "ch.offline": "The cohort board and forum require a connection. Try again online.",
  "ch.none": "You are not attached to any cohort for this course. Cohorts are created by your organisation or the teaching team.",
  "ch.boardTitle": "Group progress",
  "ch.members": "{n} member(s)",
  "ch.blocksDone": "{n} block(s) completed",
  "ch.certified": "Certified",
  "ch.avg": "Average progress: {pct}%",
  "ch.certCount": "{n} certified",
  "ch.anonNote": "Aggregated cohort progress — no individual is identified.",
  "ch.forumTitle": "Practice forum",
  "ch.newThread": "New thread",
  "ch.threadTitlePh": "Thread title (e.g. “How do you protect your morning slot?”)",
  "ch.threadBodyPh": "Your message — share a field situation, a difficulty, a tip…",
  "ch.publish": "Publish",
  "ch.noThreads": "No threads yet. Start the first discussion: a situation from your field exercises is a great starting point.",
  "ch.replies": "{n} reply(ies)",
  "ch.reply": "Reply",
  "ch.replyPh": "Your reply…",
  "ch.locked": "Thread locked by moderation.",
  "ch.anonymous": "Cohort member",
  "ob.invalidPeer": "Enter a valid name and e-mail.", "ob.step": "Step {n} of 3",
  "ob.startingPoint": "Your starting point", "ob.pamTag": "🎯 Anchor Moment",
  "ob.howTitle": "How this course works",
  "ob.howIntro": "Two minutes to understand the method — it differs from a classic course.",
  "ob.how1": "📱 Micro-sessions of 15–25 minutes, on mobile or desktop, resuming automatically where you left off. Your written answers feed the rest of the journey: once submitted, they are final.",
  "ob.how2": "🎯 Practice happens IN PARALLEL, in your real work: from Block 2, the exercises ask you to test your tools in the field — not just to think about them.",
  "ob.how3": "📓 The logbook is separate: 6 micro-entries of 5 minutes, unlocked over 15 days of real practice (D+2 → D+15). You'll get an e-mail at each opening, and a reminder if you forget. The final project builds on it — it cannot be rushed.",
  "ob.how4": "🤝 Your progress peer: a trusted person you name at the start and share your progress with — one of the secrets of journeys that reach the finish line.",
  "ob.how5": "🎓 Certification: a mini-project anchored in your reality, assessed by a human evaluator with a transparent rubric — 70/100 threshold AND a minimum per criterion: no average compensates for an insufficient criterion.",
  "ob.howCta": "Got it, let's start →",
  "ob.pamPlaceholder": "Describe your real work situation…", "ob.saveContinue": "Save and continue →",
  "ob.objective": "🎯 Course objective", "ob.whichProfile": "Which profile fits you best?", "ob.continue": "Continue →",
  "ob.peerTitle": "Your progress peer", "ob.peerDescPre": "Choose someone who will be told about your achievements. ",
  "ob.peerMandatory": "Mandatory step", "ob.peerDescPost": " — social accountability is part of the journey.",
  "ob.name": "Name", "ob.namePh": "Colleague / mentor name", "ob.email": "Email", "ob.emailPh": "email@example.com",
  "ob.validate": "Confirm my progress peer", "ob.medal": "In", "ob.doneTitle": "Micro-session 0.1 — Onboarding completed!",
  "ob.doneDesc": "One step left before your entry badge: the trigger video. It starts right after.", "ob.startCourse": "Continue the course →",
  "sess.unavailableOffline": "Course unavailable offline.", "sess.triggerVideo": "Trigger video",
  "sess.thisSession": "⏱️ This micro-session: {dur}", "sess.recall": "↩︎ Recap — {title}", "sess.keyTakeaway": "Key takeaway",
  "sess.videoUnavailable": "⚠️ The video isn't available right now. You can still continue the micro-session.",
  "sess.skipExercise": "Skip to the exercise →", "sess.finishSession": "Finish the micro-session →",
  "nav.backCourse": "← Course", "common.continue": "Continue →", "common.cancel": "Cancel", "home.remaining": "≈ {dur} left",
  "home.remainingSplit": "Current block: ≈ {block} · Course: ≈ {all}",
  "home.startBtn": "Start →",
  "crumb.blockDur": "Block {n} · {title} — {dur}", "crumb.itemDur": "{label} — {dur}",
  "sess.fullscreenHint": "💡 Tip: watch fullscreen (⛶). The moving text on the video (your name/e-mail) is an anti-sharing watermark — it's normal.",
  "quiz.profileSaved": "Profile recorded — every answer is valid",
  "sess.toTriggerQuiz": "Continue to the trigger quiz →",
  "sess.triggerQuizTitle": "Trigger quiz — {n} quick questions (not graded, refines your profile)",
  "sess.triggerQuizGo": "Submit my answers",
  "mission": "🎯 Your mission", "answerPlaceholder": "Your answer, grounded in your real situation…",
  "tc.gibberish": "⚠️ Some words don't seem to exist in French or English: {words}. Fix your answer to continue — the platform expects meaningful sentences.",
  "tc.tooShort": "⚠️ Write a complete answer (at least {n} words).",
  "tc.needNumber": "⚠️ This field expects a quantity — write a number (e.g. \"25%\", \"90 minutes\") or its spelled-out equivalent.",
  "tc.charsLeft": "✍️ {n} more characters (letters and spaces, not words) before you can submit — expand your answer.",
  "tc.filler": "⚠️ Your answer looks like filler text ({words}…). This exercise feeds the rest of your journey — answer with your real situation.",
  "count.min": "{n} / {min} {unit} minimum",
  "count.ok": "{n} {unit} ✓",
  "qz.diagnostic": "Diagnostic quiz", "qz.interblock": "Inter-block quiz", "qz.final": "Final quiz",
  "qz.unavailable": "Quiz unavailable.", "qz.profileTitle": "Your competency profile",
  "qz.priorities": "Your learning priorities", "qz.priority1": "Your learning priority", "qz.score": "Score: {correct}/{total}",
  "qz.notScored": "This quiz is not graded: it establishes your starting profile, and your learning priorities above follow directly from your answers.",
  "qz.finalPassed": "Final quiz passed!", "qz.finalNotYet": "Not reached yet",
  "qz.thresholdPill": "{pct}% · threshold {threshold}%", "qz.finalPassedDesc": "The certification block is unlocked.",
  "qz.finalFailDesc": "Revisit the block's sessions then try again.",
  "qz.consolidationDone": "Consolidation complete", "qz.correctCount": "{correct}/{total} correct answers",
  "qz.noPriorities": "No gap detected — every topic is mastered. Keep going to consolidate your reflexes.",
  "qz.selfDiverges": "You identified with “{self}”. Your situational diagnostic places you as “{band}”: the two diverge — the diagnostic is authoritative for the rest of the course.",
  "qz.selfConfirms": "Your situational diagnostic (“{band}”) is consistent with the profile you identified with (“{self}”).",
  "qz.selfNeutral": "You identified with “{self}”. Your situational diagnostic places you as “{band}” — it is authoritative for the rest of the course.",
  "act.scenarioContext": "Context", "act.scenarioOf": "Situation {n} / {total}", "act.scenarioDone": "Guided scenarios complete!",
  "act.selfIntro": "Rate yourself honestly on each statement — there is no right or wrong answer; this is your baseline before the action plan.",
  "act.planIntro": "Your plan for the next 30 days: one habit at a time. Describe each habit concretely — this is what your progress peer will follow.",
  "act.caseIntro": "Read the case steps, then write your analysis: it is saved and reused in Block 4.",
  "act.caseContext": "Context", "act.caseStepOf": "Step {n} of {total}",
  "act.caseSaved": "💾 Answer saved for the Block 4 certification project.",
  "act.caseAllValid": "Every answer is valid — pick the one that matches your situation.",
  "act.caseSummary": "Key takeaways", "act.caseDone": "Case study completed!",
  "act.openAnswerPh": "Your answer…",
  "act.caseAnswer": "Your analysis (transfer to your situation)",
  "ex.aiTitle": "Personalised feedback on your answer", "ex.aiLoading": "Analysing your answer…",
  "badge.unlocked": "Badge unlocked!", "badge.peerNotified": "🤝 Your progress peer has been notified",
  "jr.eyebrow": "Logbook", "jr.title": "Anchor my learning",
  "jr.intro": "A micro-entry at key intervals, grounded in your real situation (your Anchor Moment). These entries compose Section 4 of your project and count toward the mark: regularity of practice is a rubric criterion with a required minimum.",
  "jr.day": "Day D+{n}",
  "bd.eyebrow": "Your badges", "bd.title": "Certification progress", "bd.obtained": "Earned",
  "bd.entry": "Entry badge", "bd.comprehension": "Comprehension badge", "bd.practice": "Practice badge", "bd.anchoring": "Anchoring badge",
  "bd.addLinkedIn": "Add to LinkedIn", "bd.verify": "Verify", "bd.certOf": "Certification — {level}",
  "bd.publicVerify": "Public verification", "bd.submitProject": "Submit my Block 4 project →",
  "bd.blockBadges": "End-of-block badges", "bd.finalCert": "Final certification",
  "bd.certNote": "Badges are progression milestones — only the final, evaluator-validated certification counts as certification.",
  "bd.download": "⬇ Download (PDF)", "bd.transcript": "Results record (scored quizzes and activities)",
  "bd.notGraded": "not graded",
  "dl.fieldEyebrow": "Field application — mandatory", "dl.fieldTitle": "Field application",
  "dl.journalTitle": "Logbook — Day {key}", "dl.unitChars": "characters", "dl.unitWords": "words",
  "dl.notFound": "Item not found.", "dl.submit": "Submit →", "dl.submitted": "Answer submitted!",
  "dl.journalLockedAt": "This micro-entry opens on {date} (D+{day} after micro-session 4.3). You'll be notified.",
  "dl.journalLockedAfter43": "The two-week logbook opens after micro-session 4.3 (Section 3) — its entries then unlock one by one (D+2 → D+15).",
  "pj.unavailable": "Project unavailable.", "pj.eyebrow": "Block 4 · Certification", "pj.title": "Certification project",
  "pj.st.submitted": "Submitted — awaiting assignment", "pj.st.assigned": "Being evaluated",
  "pj.st.passed": "Certified 🎓", "pj.st.revision": "Resubmission requested — one resubmission within 30 days, reviewed by the same evaluator",
  "pj.st.notCertified": "Not certified — revisiting Blocks 2 or 3 is advised before a new submission",
  "pj.submittedOn": "Submitted on {date}", "pj.evaluator": "Evaluator: {name}",
  "pj.scoreLine": "Score: {score}/100", "pj.scoreThreshold": "(threshold {threshold})", "pj.evalFeedback": "Evaluator feedback",
  "pj.appeal.title": "Contest the decision (appeal)",
  "pj.appeal.intro": "You may contest in writing within 15 calendar days of the decision: tick the contested criteria and state the elements of your submission you believe were not taken into account. Your submission will be re-marked blind by another evaluator. The appeal decision is final.",
  "pj.appeal.statementPh": "Elements of my submission not taken into account…",
  "pj.appeal.submit": "File the appeal →",
  "pj.appeal.pickOne": "Tick at least one contested criterion.",
  "pj.appeal.status.OPEN": "Appeal filed — a second evaluator is being appointed",
  "pj.appeal.status.SECOND_ASSIGNED": "Appeal in progress — blind re-marking by a second evaluator",
  "pj.appeal.status.THIRD_REQUIRED": "Appeal in progress — a third evaluator will rule",
  "pj.appeal.status.THIRD_ASSIGNED": "Appeal in progress — awaiting the third evaluator's ruling",
  "pj.appeal.status.DECIDED": "Appeal concluded — final decision: {total}/100",
  "pj.appeal.final": "The appeal decision is final.",
  "pj.rubricTitle": "Evaluation rubric", "pj.rubricNote": "(visible before submitting — expand each criterion)",
  "pj.pts": "{n} pts", "pj.passThreshold": "Pass threshold: {threshold}/100",
  "pj.rubricMin": "min. {min}", "pj.whereToLook": "Where the evaluator looks for evidence: {text}",
  "pj.band": "Band {band} · {lo}–{hi} pts",
  "pj.decisionTitle": "How the decision is made",
  "pj.decisionCertified": "Certified: total ≥ {threshold}/100 AND every criterion at its minimum — no average compensates for an insufficient criterion.",
  "pj.decisionResubmit": "Resubmission requested: total below the threshold, or ONE criterion below its minimum — a single resubmission, within 30 days, reviewed by the same evaluator.",
  "pj.decisionNotCertified": "Not certified: two criteria below their minimum, or a total below 55/100.",
  "pj.writeTip": "✍️ Write full sentences with concrete, dated examples set in your context: the assessment relies on exact quotes from your submission — developed writing is your best evidence.",
  "pj.minMet": "minimum met ({min})", "pj.minMissed": "below the minimum ({min})",
  "pj.words": "{count} words — minimum {min}",
  "pj.sectionLocked": "🔒 Opens after sections 1 to 3. Missing journal entries do not block submission, but they weigh on the mark: regularity of practice is a rubric criterion with a required minimum.",
  "pj.submit": "Submit my project →", "pj.complete5": "Complete all 5 sections to submit.",
  "ex.eyebrow": "Micro-exercise — mandatory", "ex.validate": "Submit my answer",
  "ex.correct": "✓ Correct answer", "ex.review": "Needs review", "ex.feedback": "Immediate feedback", "ex.next": "Next session →",
  "rev.eyebrow": "Personalised review", "rev.title": "Your areas to improve",
  "rev.noQuiz": "Take the diagnostic quiz first to get a personalised review.",
  "rev.noErrors": "🎉 No mistakes in the diagnostic — nothing to review for now!",
  "rev.intro": "The questions you missed in the diagnostic. Re-read the correct answer and the explanation to reinforce your learning (ungraded).",
  "rev.goodAnswer": " — correct answer", "rev.yourAnswer": " — your answer", "rev.why": "Why", "rev.resume": "Resume the course →",
  "vp.speed": "Speed", "vp.speedAria": "Playback speed", "vp.quality": "Quality", "vp.auto": "Auto",
  "vp.subtitles": "Subtitles", "vp.stOff": "Off",
  "vp.source": "Source (max)", "vp.720p": "720p (HD)", "vp.480p": "480p", "vp.240p": "240p — data saver", "vp.audio": "Audio only",
  "ci.onboarding": "Introduction & starting point", "ci.case": "Case study", "ci.scenarios": "Guided scenarios",
  "ci.self": "Self-assessment", "ci.plan": "30-day action plan", "ci.journal": "Logbook D+{day}",
  "ci.msPrefix": "Micro-session", "ci.ms01": "Micro-session 0.1 — Onboarding", "ci.ms02": "Micro-session 0.2 — Trigger",
  "ci.ms02sub": "Trigger video + Quiz (not graded)", "ci.transversal": "Transversal synthesis case",
  "ci.journalGroup": "Two-week logbook",
  "quiz.q": "Question {n} / {total}", "quiz.validate": "Submit", "quiz.good": "✓ Correct", "quiz.review": "Needs review",
  "quiz.seeResult": "See my result →", "quiz.nextQuestion": "Next question →",
  "quiz.multiHint": "Multiple answers possible", "quiz.true": "True", "quiz.false": "False",
  "quiz.numPlaceholder": "Your answer (a number)", "quiz.expected": "Expected answer: {n}",
  // frozen results (first submission is final)
  "frz.note": "Answers recorded on your first attempt — viewable but no longer editable.",
  "frz.yourAnswer": "Your answer",
  "frz.viewAnswer": "View my answer",
  "frz.resultTitle": "Your results",
  "frz.retake": "Previous attempt: {pct}% (threshold: {threshold}%). Retake this quiz to unlock what follows.",
  "course.retakeFinal": "To retake",
  "quiz.shortPlaceholder": "Your answer", "quiz.accepted": "Accepted answers: {list}",
};

export const UI_TEXT_DEFAULTS: Record<UiLang, UiDict> = { fr, en };
